trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Zip the single HTML file (and anything else in the folder)
- task: ArchiveFiles@2
  displayName: 'Zip the HTML file'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    # Naming the zip 'website.zip' so it's easy to find
    archiveFile: '$(Build.ArtifactStagingDirectory)/website.zip'
    replaceExistingArchive: true

# 2. Upload the zip for deployment
- task: PublishBuildArtifacts@1
  displayName: 'Publish the Zip'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'